[scrolling]
history = 100000
multiplier = 3

[colors]
draw_bold_text_with_bright_colors = true

[colors.cursor]
cursor     = "#29A63E"
text       = "#eff0eb"

[colors.primary]
background = "#000000"
foreground = "#D8D8B3" # light beige
# foreground = "#F5F5DC" # soft ivory
# foreground = "#D8E6E0" # pale mint
# foreground = "#D3D3D3" # light grey
# foreground = "#FAFAD2" # warm white

[selection]
save_to_clipboard = true

[mouse]
hide_when_typing = true
