[terminal]
shell = { program = "wsl.exe" }

[font]
size = 12 
normal = { family = "Cascadia Mono" }

[window]
decorations = "None"
# startup_mode = "Windowed" | "Maximized" | "Fullscreen" | "SimpleFullscreen"
startup_mode = "Maximized"
option_as_alt = "Both"

